name: Spock

on:
  pull_request:
    branches:
      - main
      - release/*
    paths:
      - 'cloudformation/templates/sagemaker-notebook.yaml'
      - '**spock**'
  push:
    branches:
      - main
      - release/*
      - feat/* # Enable feature branches deployment for build phase
    paths:
      - 'cloudformation/templates/sagemaker-notebook.yaml'
      - '**spock**'
      - 'README.md'

env:
  STACK_NAME: 'sagemaker-notebook-spock'
  STACK_TEMPLATE: 'sagemaker-notebook'
  STACK_PARAMETERS: 'sagemaker-notebook-spock'
  AWS_ACCOUNT_DEV: '731842666869' #insights-data-science-dev
  AWS_ACCOUNT_TST: '734262042937' #insights-data-science-tst
  AWS_ACCOUNT_STG: '723124220550' #insights-data-science-stg
  AWS_ACCOUNT_PRD: '004872082659' #insights-data-science-prd
  IAM_ASSUME_ROLE_TIMEOUT: '3600'
  AWS_REGION: 'ap-southeast-2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello world"
